// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDytEtSd_rwP0CmdEBHvDHeMID1mK536zs',
    appId: '1:855338350053:web:4e9a523d24a48a03952b0c',
    messagingSenderId: '855338350053',
    projectId: 'social-app-a5feb',
    authDomain: 'social-app-a5feb.firebaseapp.com',
    storageBucket: 'social-app-a5feb.appspot.com',
    measurementId: 'G-R25EDBC890',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuodDxbdEkPnfBRTLsZH9XUzWazXoJFiE',
    appId: '1:855338350053:android:7ed136536656b1cf952b0c',
    messagingSenderId: '855338350053',
    projectId: 'social-app-a5feb',
    storageBucket: 'social-app-a5feb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDPfijX3zB9YjEbN-HQGxX7B80uoOtF0w',
    appId: '1:855338350053:ios:1db5d6095fdca8d0952b0c',
    messagingSenderId: '855338350053',
    projectId: 'social-app-a5feb',
    storageBucket: 'social-app-a5feb.appspot.com',
    iosClientId: '855338350053-l80fjuqp9iejl9eu0ggjc4hpl563212d.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDPfijX3zB9YjEbN-HQGxX7B80uoOtF0w',
    appId: '1:855338350053:ios:34098e9dea3e57cc952b0c',
    messagingSenderId: '855338350053',
    projectId: 'social-app-a5feb',
    storageBucket: 'social-app-a5feb.appspot.com',
    iosClientId: '855338350053-hgr28452uo701s946doshcdu9r2cnks7.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
